### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'atom://config'

### ISSUE THREAD

**Issue by xuexianwu** [hansec/autocomplete-fortran#2] opened 2016-06-17 02:45 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [autocomplete-fortran](https://github.com/hansec/autocomplete-fortran) package, v0.6.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'atom://config'

```
At fs.js:856

Error: ENOENT: no such file or directory, scandir 'atom://config'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:497:28)
    at FortranProvider.module.exports.FortranProvider.findModFiles (/Users/xwxue/.atom/packages/autocomplete-fortran/lib/fortran-provider.coffee:106:18)
    at FortranProvider.module.exports.FortranProvider.rebuildIndex (/Users/xwxue/.atom/packages/autocomplete-fortran/lib/fortran-provider.coffee:66:6)
    at FortranProvider.module.exports.FortranProvider.getSuggestions (/Users/xwxue/.atom/packages/autocomplete-fortran/lib/fortran-provider.coffee:196:8)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -4:44.6.0 window:install-shell-commands (atom-text-editor.editor.is-focused)
     -3:58.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:53.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:53.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:53.4.0 editor:indent (atom-text-editor.editor.is-focused)
  6x -2:48.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
autocomplete-fortran, v0.6.0
language-openmp, v0.2.0

# Dev
No dev packages
```

**Comment by hansec** [comment] 2016-06-17 14:54
I believe this error is due to an invalid or inaccessible module directory specified in your `.ac_fortran` file. I added some code to catch this failure and report the offending directory. Can you update the autocomplete-fortran package and see if this error still occurs?

Thanks for the feedback.

**Comment by hansec** [comment] 2016-06-30 18:19
I has been about 2 weeks so I am going to close this issue. If the problem is still present let me know I will reopen it.

**Closed as completed by hansec** 2016-06-30 18:19 UTC
